### ISSUE TITLE
prysm latest releases missing

### ISSUE THREAD

**Issue by nicolasochem** [ethpandaops/eth-client-docker-image-builder#111]
I don't see v4.1.1 in the [docker repo](https://hub.docker.com/r/ethpandaops/prysm/tags?page=1) but it's been released for 2 weeks.

**Comment by nicolasochem** [comment]
Same with 4.2.1. I only see rc1. Please fix.

**Comment by barnabasbusa** [comment]
You should be able to use prysm's upstream images. 

If you are using the containers on our helm charts, you will be able to use the upstream images there too, once this PR is closed: https://github.com/ethpandaops/ethereum-helm-charts/pull/280

**Comment by barnabasbusa** [comment]
The PR mentioned above is merged. And the upstream images now are working with our helm charts. We will not be making tagged releases in the future. Please use the upstream images for production purposes.
