### ISSUE TITLE
Git commit hash is only short hash

### ISSUE THREAD

**Issue by nflaig** [ethpandaops/eth-client-docker-image-builder#212]
I noticed that Lodestar images built via this repo do not have access to full commit hash.

The commit set here which is used by Lodestar internally
https://github.com/ethpandaops/eth-client-docker-image-builder/blob/37165d03c84fbe924ace7deb2f185e8af86717fd/lodestar/build.sh#L6

is only the short hash, as retrieved here via git log
https://github.com/ethpandaops/eth-client-docker-image-builder/blob/37165d03c84fbe924ace7deb2f185e8af86717fd/.github/actions/deploy/action.yml#L65

This is not a big deal usually as we only use the first 7 characters to be consistent with Github when displaying our version but the new `engine_getClientVersionV1` engine api method [expects 4 bytes](https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/identification.md#clientversionv1), ie. the first 8 characters.

So far it seems like ELs are pretty lax in parsing this data so I don't think it's a big issue.

**Comment by nflaig** [comment]
so seems like there was an issue related to this before https://github.com/paradigmxyz/reth/pull/9137 but with Lighthouse, but that's on the CL side which cares more about the commit value since it's included in the graffiti, I don't think ELs bother at the moment

**Comment by parithosh** [comment]
cc @Savid

**Comment by Savid** [comment]
updated in #216 

before;
```bash
docker run -it ethpandaops/lodestar:unstable-d55bb2d beacon
info: Lodestar network=mainnet, version=v1.23.1/d55bb2d, commit=d55bb2d
```

after
```
docker run -it ethpandaops/lodestar:unstable-test-e353f67 beacon
info: Lodestar network=mainnet, version=v1.23.1/e353f67, commit=e353f67426581e622c6df83c30992b4a28dcb617
```
